name: test-and-build

on:
  push: {}

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:ffde637e94809e3471daaa46186e64fb49b90aa0472f2a713499528776910816
      env:
        CGO_ENABLED: 0

    runs-on: forgejo

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/preserve/preserve

      - name: Lint and test code
        run: make lint test

      - name: Execute Trivy scan
        run: |
          trivy fs . \
            --dependency-tree \
            --exit-code 1 \
            --format table \
            --ignore-unfixed \
            --quiet \
            --scanners misconfig,license,secret,vuln \
            --severity HIGH,CRITICAL

      - name: Local Build
        run: go build .
